name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker container
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ghcr.io/${{ github.repository }}/fajs-api-server
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
